# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

silent: true

vars:
  HOME:
    sh: echo $HOME

tasks:
  default:
    deps: 
      - install

  help:
    desc: "Show information about K3s"
    cmds:
      - echo "{{.USAGE}}"

  install:
    desc: "Install K3s"
    summary: >
      Install K3s server with default configuration
    run: once
    status:
      - command -v k3s >/dev/null 2>&1
    cmds:
      - curl -sfL https://get.k3s.io | sh -
      - sudo chmod 644 /etc/rancher/k3s/k3s.yaml
      - |
        mkdir -p {{.HOME}}/.kube
        sudo cp /etc/rancher/k3s/k3s.yaml {{.HOME}}/.kube/config
        sudo chown $(id -u):$(id -g) {{.HOME}}/.kube/config
        chmod 600 {{.HOME}}/.kube/config
      - echo 'export KUBECONFIG={{.HOME}}/.kube/config' >> {{.HOME}}/.bashrc
      - echo "Installation complete! Run 'source ~/.bashrc' to use kubectl"

  start:
    desc: "Start K3s service"
    cmds:
      - sudo systemctl start k3s

  stop:
    desc: "Stop K3s service"
    cmds:
      - sudo systemctl stop k3s

  status:
    desc: "Check K3s service status"
    cmds:
      - sudo systemctl status k3s

  uninstall:
    desc: "Uninstall K3s"
    summary: Remove K3s and all its data
    cmds:
      - /usr/local/bin/k3s-uninstall.sh

  token:
    desc: "Get node token"
    summary: Display node token for joining agents
    cmds:
      - sudo cat /var/lib/rancher/k3s/server/node-token

  logs:
    desc: "View K3s logs"
    cmds:
      - sudo journalctl -u k3s {{.CLI_ARGS}}
