# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  HOME:
    sh: echo $HOME

tasks:
  default:
    desc: "Preconfigure and install K3s"
    run: once
    cmds:
      - task: preconfigure
      - task: install

  preconfigure:
    desc: "Configure system prerequisites"
    run: once
    cmds:
      - task: install-deps
      - task: disable-swap
      - task: configure-firewall

  install-deps:
    desc: "Install required system dependencies"
    status:
      - which curl
      - which ufw
    cmds:
      - sudo apt-get install -y curl ufw

  disable-swap:
    desc: "Disable system swap"
    status:
      - test "$(swapon --show)" = ""
    cmds:
      - sudo swapoff -a
      - sudo sed -i '/ swap / s/^/#/' /etc/fstab

  configure-firewall:
    desc: "Configure UFW for K3s"
    run: once
    cmds:
      - sudo ufw allow 6443/tcp # Kubernetes API
      - sudo ufw allow from 10.42.0.0/16 # Pod network
      - sudo ufw allow from 10.43.0.0/16 # Service network
      - sudo ufw allow 8472/udp # Flannel VXLAN
      - sudo ufw allow 51820/udp # Flannel WireGuard (IPv4)
      - sudo ufw allow 51821/udp # Flannel WireGuard (IPv6)
      - sudo ufw --force enable

  install:
    desc: "Install K3s"
    run: once
    status:
      - command -v k3s >/dev/null 2>&1
    cmds:
      - curl -sfL https://get.k3s.io | sudo sh -
      - sudo systemctl enable --now k3s
      - sudo chmod 644 /etc/rancher/k3s/k3s.yaml

  setup-kubectl:
    desc: "Configure kubectl"
    run: once
    cmds:
      - mkdir -p {{.HOME}}/.kube
      - sudo cp /etc/rancher/k3s/k3s.yaml {{.HOME}}/.kube/config
      - sudo chown $(id -u):$(id -g) {{.HOME}}/.kube/config
      - sudo chmod 600 {{.HOME}}/.kube/config

  uninstall:
    desc: "Remove K3s and cleanup"
    cmds:
      - sudo /usr/local/bin/k3s-uninstall.sh || true
      - sudo rm -f {{.HOME}}/.kube/config
