# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  HOME:
    sh: echo $HOME

tasks:
  default:
    deps:
      - task: install

  install:
    desc: "Install Bun"
    run: once
    status:
      - command -v bun >/dev/null 2>&1
    cmds:
      - curl -fsSL https://bun.sh/install | bash
      - sudo mv "{{.HOME}}/.bun/bin/bun" /usr/local/bin/
      - sudo chown root:root /usr/local/bin/bun
      - sudo chmod 755 /usr/local/bin/bun
      - bun --version

  test:
    desc: "Test Bun installation"
    deps:
      - task: test:version
      - task: test:help
      - task: test:create

  test:version:
    internal: true
    cmds:
      - test "$(bun --version 2>&1 | grep -c "bun")" -eq 1

  test:help:
    internal: true
    cmds:
      - test "$(bun --help 2>&1 | grep -c "USAGE")" -eq 1

  test:create:
    internal: true
    cmds:
      - bun create test-app
      - test -d test-app
      - rm -rf test-app
