# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  HOME:
    sh: echo $HOME

tasks:
  default:
    deps:
      - task: install

  install:
    desc: "Install Bun"
    run: once
    status:
      - command -v bun >/dev/null 2>&1
    cmds:
      - curl -fsSL https://bun.sh/install | bash
      - sudo mv "{{.HOME}}/.bun/bin/bun" /usr/local/bin/
      - sudo chown root:root /usr/local/bin/bun
      - sudo chmod 755 /usr/local/bin/bun
      - /usr/local/bin/bun --version
      - bun --version
