# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  install:
    desc: "Install bun"
    silent: true
    run: once
    status:
      - command -v bun >/dev/null 2>&1
    deps:
      - task: install-deps
    vars:
      HOME:
        sh: echo $HOME
    cmds:
      - |
        curl -fsSL https://bun.sh/install | bash
        sudo mv {{.HOME}}/.bun/bin/bun /usr/local/bin/
        sudo chown root:root /usr/local/bin/bun
        sudo chmod 755 /usr/local/bin/bun

  install-deps:
    desc: "Install bun dependencies"
    cmds:
      - sudo apt install unzip
