# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    desc: "Install uv"
    deps:
      - task: install

  install:
    desc: "Install uv"
    vars:
      DOWNLOAD_URL: "https://astral.sh/uv/install.sh"
      INSTALL_DIR: "/usr/local/bin"
    run: once
    status:
      - command -v uv >/dev/null 2>&1
    cmds:
      - curl -fsSLO "{{.DOWNLOAD_URL}}"
      - defer: rm -f install.sh
      - chmod +x install.sh
      - UV_INSTALL_DIR="{{.INSTALL_DIR}}" sudo -E ./install.sh
      - uv --version
