# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  TASKFILE_DIR:
    sh: pwd
  ROOT_DIR:
    sh: git rev-parse --show-toplevel

tasks:
  # Testing tasks
  act:matrix:test:
    desc: Run matrix testing for a specific tool
    vars:
      TOOL:
        sh: echo "$TOOL"
    cmds:
      - |
        if [ -z "$TOOL" ]; then
          echo "Error: TOOL variable is required"
          echo "Usage: task act:matrix:test TOOL=<toolname>"
          exit 1
        fi
        
        cd {{.ROOT_DIR}} && act -W .github/workflows/test-{{.TOOL}}.yml \
          -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest \
          -P catthehacker/ubuntu:full=ghcr.io/catthehacker/ubuntu:act-latest

  # Workflow generation tasks
  workflow:generate:
    desc: Generate GitHub workflow for a specific taskfile
    deps: ['../../../:go:install']
    cmds:
      - go run generate.go -type workflow -taskfile {{.TASKFILE_DIR}} -root {{.ROOT_DIR}}

  workflows:generate:
    desc: Generate GitHub workflows for all taskfiles
    deps: ['../../../:go:install']
    cmds:
      - |
        for dir in {{.ROOT_DIR}}/.taskfiles/*/; do
          if [ -d "$dir" ]; then
            task: workflow:generate TASKFILE_DIR="$dir"
          fi
        done

  # README tasks
  readme:update:
    desc: Update README with taskfile status badges
    deps: ['../../../:go:install']
    cmds:
      - go run generate.go -type readme -root {{.ROOT_DIR}}
