# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: '3'

vars:
  IMAGE_NAME: ghcr.io/drengskapur/taskfile-tester
  IMAGE_TAG: develop

tasks:
  default:
    deps: [build]

  build:
    desc: Build the act runner image
    cmds:
      - docker build -t {{.IMAGE_NAME}}:{{.IMAGE_TAG}} .

  test:
    desc: Test a specific taskfile in multiple OS environments
    deps: [build]
    cmds:
      - |
        TASKFILE={{.CLI_ARGS}} docker compose up \
          --abort-on-container-exit \
          --exit-code-from act-runner

  generate:
    desc: Generate workflow files
    cmds:
      - go run generate.go -type workflow -taskfile {{.CLI_ARGS}}

  update:
    desc: Update all workflow files
    cmds:
      - ./update_workflows.sh
