---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set: [pipefail]
shopt: [globstar]

# vars:
#   VARIABLE: value

# dotenv:
#   - .env

# env:
#   ENVIRONMENT_VARIABLE: "{{.VARIABLE}}/folder"

includes:
  aws: .taskfiles/aws
  digitalocean: .taskfiles/digitalocean
  docker: .taskfiles/docker
  install: .taskfiles/install
  k3s: .taskfiles/k3s
  mix: .taskfiles/mix
  rclone: .taskfiles/rclone
  terraform: .taskfiles/terraform

tasks:
  default:
    cmd: task --list
    silent: true

  noop:
    internal: true
    silent: true
    cmd: noop() { :; }
