# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    deps:
      - task: install

  install:
    desc: "Install Docker"
    run: once
    vars:
      USER:
        sh: whoami
    status:
      - command -v docker >/dev/null 2>&1
    cmds:
      - curl -fsSL https://get.docker.com | sh
      - |
        if [ "$(id -u)" != "0" ]; then
          sudo usermod -aG docker "{{.USER}}"
          sudo systemctl enable docker
          sudo systemctl start docker
        else
          usermod -aG docker "{{.USER}}"
          systemctl enable docker
          systemctl start docker
        fi
      - docker version

  test:
    desc: "Test Docker installation and basic functionality"
    deps:
      - install
    cmds:
      - docker version
      - docker info
      - |
        # Test basic container functionality
        docker run --rm hello-world
