# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  install:
    desc: "Install Docker"
    run: once
    status:
      - command -v docker >/dev/null 2>&1
    vars:
      USER:
        sh: whoami
    cmds:
      - curl -fsSL https://get.docker.com | sh
      - sudo usermod -aG docker "{{.USER}}"
      - sudo systemctl enable docker
      - sudo systemctl start docker
