# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  HOME:
    sh: echo $HOME
  COMMAND_PREFIX:
    sh: if [ "$(id -u)" != "0" ]; then echo "sudo"; else echo ""; fi

tasks:
  default:
    deps:
      - task: install

  install:
    desc: Install pnpm
    run: once
    status:
      - command -v pnpm
    cmds:
      - |
        {{.COMMAND_PREFIX}} apt-get update
      - |
        {{.COMMAND_PREFIX}} apt-get install --no-install-recommends -y curl
      - curl -fsSLo pnpm "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linux-x64"
      - |
        {{.COMMAND_PREFIX}} chmod 755 pnpm
      - |
        {{.COMMAND_PREFIX}} mv pnpm /usr/local/bin/pnpm
      - |
        {{.COMMAND_PREFIX}} chown root:root /usr/local/bin/pnpm
      - /usr/local/bin/pnpm --version
