# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  install:
    desc: "Install pnpm"
    run: once
    status:
      - command -v pnpm >/dev/null 2>&1
    cmds:
      - curl -fsSL https://get.pnpm.io/install.sh | sh -
