# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    deps:
      - task: install

  install:
    desc: "Install pnpm"
    deps:
      - task: node-check
    run: once
    status:
      - command -v pnpm >/dev/null 2>&1
    cmds:
      - curl -fsSL https://get.pnpm.io/install.sh | sh -
      - source $HOME/.bashrc
      - pnpm --version

  test:
    desc: "Test pnpm installation"
    cmds:
      - |
        act -j test-local -W .taskfiles/pnpm/test-pnpm.yml -P ubuntu-22.04=ubuntu:22.04 --container-options "--privileged --rm" --eventpath <(echo '{"act": true}')

  node-check:
    desc: "Check Node.js installation"
    internal: true
    status:
      - command -v node >/dev/null 2>&1
    cmds:
      - echo "Node.js is required. Please install Node.js first using 'task node:install'"
      - exit 1
