# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:

tasks:
  default:
    deps: 
      - install

  install:
    desc: "Install Terraform"
    vars:
      LATEST_VERSION:
        sh: curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version'
      DOWNLOAD_URL: "https://releases.hashicorp.com/terraform/{{.LATEST_VERSION}}/terraform_{{.LATEST_VERSION}}_linux_amd64.zip"
    run: once
    status:
      - command -v terraform >/dev/null 2>&1
    defer:
      - rm -f terraform_{{.LATEST_VERSION}}_linux_amd64.zip
    cmds:
      - curl -sLO "{{.DOWNLOAD_URL}}"
      - unzip -o terraform_{{.LATEST_VERSION}}_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - sudo chown root:root /usr/local/bin/terraform
      - sudo chmod 755 /usr/local/bin/terraform
      - terraform version
