# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    deps:
      - task: install

  install:
    desc: "Install Terraform"
    run: once
    vars:
      COMMAND_PREFIX:
        sh: if [ "$(id -u)" != "0" ]; then echo "sudo"; fi
      LATEST_VERSION:
        sh: curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version'
      DOWNLOAD_URL: "https://releases.hashicorp.com/terraform/{{.LATEST_VERSION}}/terraform_{{.LATEST_VERSION}}_linux_amd64.zip"
    status:
      - command -v terraform
    cmds:
      - defer: rm -f terraform_linux_amd64.zip
      - curl -fsSLo terraform.zip "{{.DOWNLOAD_URL}}"
      - unzip -o terraform.zip
      - chmod 755 terraform
      - |
        {{.COMMAND_PREFIX}} mv terraform /usr/local/bin/terraform
      - |
        {{.COMMAND_PREFIX}} chown root:root /usr/local/bin/terraform
      - /usr/local/bin/terraform --version
