# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    deps:
      - task: install

  install:
    desc: "Install helm"
    vars:
      LATEST_VERSION:
        sh: curl -s https://api.github.com/repos/helm/helm/releases/latest | jq -r '.tag_name | ltrimstr("v")'
      DOWNLOAD_URL: "https://get.helm.sh/helm-v{{.LATEST_VERSION}}-linux-amd64.tar.gz"
    run: once
    status:
      - command -v helm >/dev/null 2>&1
    cmds:
      - defer: rm -f helm-v{{.LATEST_VERSION}}-linux-amd64.tar.gz
      - curl -sLO "{{.DOWNLOAD_URL}}"
      - tar xf helm-v{{.LATEST_VERSION}}-linux-amd64.tar.gz
      - |
        if [ "$(id -u)" != "0" ]; then
          sudo mv linux-amd64/helm /usr/local/bin/
          sudo chown root:root /usr/local/bin/helm
          sudo chmod 755 /usr/local/bin/helm
        else
          mv linux-amd64/helm /usr/local/bin/
          chown root:root /usr/local/bin/helm
          chmod 755 /usr/local/bin/helm
        fi
      - helm version

  test:
    desc: "Test helm installation and functionality"
    deps:
      - install
    cmds:
      - helm version
      - |
        # Initialize helm repo
        helm repo add stable https://charts.helm.sh/stable
        helm repo update
        
        # Create a test chart
        helm create test-chart
        
        # Test chart linting
        helm lint test-chart
        
        # Clean up
        rm -rf test-chart
