name: Test Helm Installation

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.taskfiles/helm/**'
  push:
    branches: [ main, develop ]
    paths:
      - '.taskfiles/helm/**'

jobs:
  test-local:
    name: Test helm installation (Local)
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
      options: --privileged
    steps:
      - uses: actions/checkout@v3

      - name: Install base system utilities
        run: |
          apt-get update
          apt-get install -y \
            ca-certificates \
            curl \
            jq

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install helm
        working-directory: .taskfiles/helm
        run: task install

      - name: Test helm installation
        working-directory: .taskfiles/helm
        run: task test

      - name: Complete job
        run: echo "Test completed successfully"

  test-github:
    name: Test helm installation (GitHub)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install helm
        working-directory: .taskfiles/helm
        run: task install

      - name: Test helm installation
        working-directory: .taskfiles/helm
        run: task test

      - name: Complete job
        run: echo "Test completed successfully"
