# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  HOME:
    sh: echo $HOME
  ACTRC: |-
    -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
    -P ubuntu-22.04=ghcr.io/catthehacker/ubuntu:act-22.04
    -P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04

tasks:
  default:
    deps:
      - task: install

  install:
    desc: "Install act"
    vars:
      COMMAND_PREFIX:
        sh: if [ "$(id -u)" != "0" ]; then echo "sudo"; fi
      LATEST_VERSION:
        sh: curl -s https://api.github.com/repos/nektos/act/releases/latest | jq -r '.tag_name | ltrimstr("v")'
      DOWNLOAD_URL: https://github.com/nektos/act/releases/download/v{{.LATEST_VERSION}}/act_Linux_x86_64.tar.gz
    run: once
    cmds:
      - defer: rm -rf act_Linux_x86_64.tar.gz LICENSE README.md
      - |
        {{.COMMAND_PREFIX}} apt-get update
      - |
        {{.COMMAND_PREFIX}} apt-get install -y jq
      - curl -sLo act_Linux_x86_64.tar.gz "{{.DOWNLOAD_URL}}"
      - tar xf act_Linux_x86_64.tar.gz
      - |
        {{.COMMAND_PREFIX}} chmod 755 act
      - |
        {{.COMMAND_PREFIX}} mkdir -p /usr/local/bin
      - |
        {{.COMMAND_PREFIX}} mv act /usr/local/bin/act
      - |
        {{.COMMAND_PREFIX}} chown root:root /usr/local/bin/act
      - echo "{{.ACTRC}}" > "{{.HOME}}/.actrc"
      - /usr/local/bin/act --version
