name: Test Act Installation

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.taskfiles/act/**'
  push:
    branches: [ main, develop ]
    paths:
      - '.taskfiles/act/**'

jobs:
  test-local:
    name: Test Act installation (Local)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install Act
        working-directory: .taskfiles/act
        run: task install

      - name: Verify installation
        run: |
          command -v act >/dev/null 2>&1 || (echo "act not found" && exit 1)
          act --version

      - name: Complete job
        run: echo "Test completed successfully"
