# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    deps:
      - install

  install:
    desc: Install rclone
    vars:
      COMMAND_PREFIX:
        sh: if [ "$(id -u)" != "0" ]; then echo "sudo"; fi
    run: once
    status:
      - command -v rclone
    cmds:
      # Install dependencies
      - |
        {{.COMMAND_PREFIX}} apt-get update
      - |
        {{.COMMAND_PREFIX}} apt-get install --no-install-recommends -y fuse curl
      # Force reinstall by temporarily moving binary
      - |
        if command -v rclone >/dev/null 2>&1; then
          {{.COMMAND_PREFIX}} mv /usr/bin/rclone /usr/bin/rclone.bak
        fi
      # Install rclone
      - |
        curl https://rclone.org/install.sh | {{.COMMAND_PREFIX}} bash
      # Cleanup backup if exists
      - |
        if [ -f /usr/bin/rclone.bak ]; then
          {{.COMMAND_PREFIX}} rm -f /usr/bin/rclone.bak
        fi
      # Verify installation
      - /usr/bin/rclone version
