# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    cmds:
      - task: install

  install:
    desc: "Install rclone"
    summary: Install rclone and FUSE support for cloud storage mounting
    run: once
    deps: [fuse:install]
    status:
      - command -v rclone >/dev/null 2>&1
    cmds:
      - curl https://rclone.org/install.sh | sudo bash
      - rclone version

  update:
    desc: "Update rclone to the latest version"
    run: once
    status:
      - rclone selfupdate | grep -q "rclone version"
    cmds:
      - rclone selfupdate
      - echo "rclone has been updated to the latest version"

  fuse:install:
    internal: true
    desc: "Install FUSE support"
    summary: Install FUSE dependencies required for mounting cloud storage
    run: once
    status:
      - command -v fusermount >/dev/null 2>&1
    cmds:
      - sudo apt update
      - sudo apt install -y fuse
