# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  COMMAND_PREFIX:
    sh: if [ "$(id -u)" != "0" ]; then echo "sudo"; fi

tasks:
  default:
    deps:
      - task: install

  install:
    desc: Install rclone
    run: once
    status:
      - command -v rclone
    cmds:
      - |
        {{.COMMAND_PREFIX}} apt-get update
      - |
        {{.COMMAND_PREFIX}} apt-get install --no-install-recommends -y fuse curl
      - |
        curl https://rclone.org/install.sh | {{.COMMAND_PREFIX}} bash
      - rclone version
