# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  COMMAND_PREFIX:
    sh: if [ "$(id -u)" != "0" ]; then echo "sudo"; fi

tasks:
  default:
    deps:
      - task: install

  install:
    desc: Install rclone
    vars:
      COMMAND_PREFIX:
        sh: if [ "$(id -u)" != "0" ]; then echo "sudo"; fi
    run: once
    status:
      - command -v rclone
    cmds:
      # Install dependencies
      - |
        {{.COMMAND_PREFIX}} apt-get update
      - |
        {{.COMMAND_PREFIX}} apt-get install --no-install-recommends -y curl unzip
      # Install rclone (exit code 3 means already up to date)
      - |
        curl https://rclone.org/install.sh | {{.COMMAND_PREFIX}} bash || [ $? -eq 3 ]
      # Verify installation
      - /usr/bin/rclone --version
