# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  install:
    desc: Install Ultracite and its dependencies
    cmds:
      - pnpm add -D --save-exact ultracite @biomejs/biome

  init:
    desc: Initialize Ultracite configuration
    deps: [install]
    cmds:
      - |
        cat > biome.json << 'EOF'
        {
          "$schema": "https://biomejs.dev/schemas/1.9.4/schema.json",
          "extends": ["ultracite"]
        }
        EOF
      - |
        mkdir -p .vscode
        cat > .vscode/settings.json << 'EOF'
        {
          "typescript.tsdk": "node_modules/typescript/lib",
          "editor.defaultFormatter": "biomejs.biome",
          "editor.formatOnSave": true,
          "editor.formatOnPaste": true,
          "emmet.showExpandedAbbreviation": "never",
          "editor.codeActionsOnSave": {
            "quickfix.biome": "explicit",
            "source.organizeImports.biome": "explicit"
          },
          "[typescript]": {
            "editor.defaultFormatter": "biomejs.biome"
          },
          "[json]": {
            "editor.defaultFormatter": "biomejs.biome"
          },
          "[javascript]": {
            "editor.defaultFormatter": "biomejs.biome"
          },
          "[jsonc]": {
            "editor.defaultFormatter": "biomejs.biome"
          },
          "[typescriptreact]": {
            "editor.defaultFormatter": "biomejs.biome"
          }
        }
        EOF

  lint:
    desc: Run Ultracite linting
    deps: [install]
    cmds:
      - npx ultracite

  format:
    desc: Format code with Biome
    deps: [install]
    cmds:
      - npx @biomejs/biome format --write .
