# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    deps:
      - task: install

  install:
    desc: "Install DigitalOcean tools"
    deps:
      - task: install:doctl
      - task: install:metrics-agent

  install:doctl:
    desc: "Install doctl CLI"
    vars:
      LATEST_VERSION:
        sh: curl -s https://api.github.com/repos/digitalocean/doctl/releases/latest | jq -r '.tag_name | sub("^v"; "")'
      DOWNLOAD_URL: "https://github.com/digitalocean/doctl/releases/download/v{{.LATEST_VERSION}}/doctl-{{.LATEST_VERSION}}-linux-amd64.tar.gz"
    run: once
    status:
      - command -v doctl >/dev/null 2>&1
    defer:
      - rm -f doctl.tar.gz
    cmds:
      - curl -sLO "{{.DOWNLOAD_URL}}" -o doctl.tar.gz
      - tar xf doctl.tar.gz
      - sudo mv doctl /usr/local/bin
      - doctl version

  install:metrics-agent:
    desc: "Install Metrics Agent"
    run: once
    defer:
      - rm -f install.sh
    cmds:
      - curl -sSL https://repos.insights.digitalocean.com/install.sh -o install.sh
      - sudo bash install.sh

  debug:cloudinit:
    desc: "Debug Cloud Init logs"
    cmds:
      - cat /var/log/cloud-init-output.log | grep userdata
