# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  COMMAND_PREFIX:
    sh: if [ "$(id -u)" != "0" ]; then echo "sudo"; else echo ""; fi
  LATEST_VERSION:
    sh: curl -s https://api.github.com/repos/jqlang/jq/releases/latest | grep -o 'jq-[0-9.]*' | head -1 | cut -d'-' -f2

tasks:
  default:
    deps:
      - install

  install:
    desc: Install jq
    run: once
    status:
      - command -v jq
    cmds:
      - curl -fsSLo jq https://github.com/jqlang/jq/releases/download/jq-{{.LATEST_VERSION}}/jq-linux-amd64
      - |
        {{.COMMAND_PREFIX}} chmod 755 jq
      - |
        {{.COMMAND_PREFIX}} mv jq /usr/local/bin/jq
      - |
        {{.COMMAND_PREFIX}} chown root:root /usr/local/bin/jq
      - jq --version
