name: Test jq Installation

on:
  push:
    paths:
      - ".taskfiles/jq/**"
  pull_request:
    paths:
      - ".taskfiles/jq/**"
  workflow_dispatch:

jobs:
  test:
    name: Test jq installation
    runs-on: ubuntu-22.04
    if: github.repository == 'drengskapur/taskfile' && !contains(github.event.act, 'true')
    container:
      image: ubuntu:22.04
      options: --privileged --user root --rm
    env:
      HOME: /root
      PATH: /bin:/usr/bin:/usr/local/bin
    defaults:
      run:
        shell: /bin/sh -e {0}
    steps:
      - uses: actions/checkout@v3

      - name: Install base system utilities
        run: |
          apt-get update
          apt-get install -y bash curl sudo ca-certificates

      - name: Cache Task binary
        id: cache-task
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/task
          key: ${{ runner.os }}-task-${{ hashFiles('**/test.yml') }}

      - name: Install Task
        if: steps.cache-task.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          task --version

      - name: Install jq
        run: task install

  test-local:
    name: Test jq installation (Local)
    runs-on: ubuntu-22.04
    if: contains(github.event.act, 'true')
    container:
      image: ubuntu:22.04
      options: --privileged --user root --rm
    env:
      HOME: /root
      PATH: /bin:/usr/bin:/usr/local/bin
    defaults:
      run:
        shell: /bin/sh -e {0}
    steps:
      - uses: actions/checkout@v3

      - name: Install base system utilities
        run: |
          apt-get update
          apt-get install -y bash curl sudo ca-certificates

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          task --version

      - name: Install jq
        run: task install
