# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  install:
    run: once
    deps:
      - task: install:jq
    vars:
      VERSION:
        sh: |
          curl -sL https://api.github.com/repos/direnv/direnv/releases/latest |
          jq -r '.tag_name' |
          tr -d 'v'
    status:
      - command -v direnv >/dev/null 2>&1
    cmds:
      - |
        curl -fsSL "https://github.com/direnv/direnv/releases/download/v{{.VERSION}}/direnv.linux-amd64" -o direnv
        sudo mv direnv /usr/local/bin/
        sudo chown root:root /usr/local/bin/direnv
        sudo chmod 755 /usr/local/bin/direnv

  install:jq:
    run: once
    vars:
      LATEST_VERSION:
        sh: |
          curl -s https://api.github.com/repos/jqlang/jq/releases/latest | grep '"tag_name":' | sed -E 's/.*"tag_name": "jq-([^"]+)".*/\1/'
      DOWNLOAD_URL: "https://github.com/jqlang/jq/releases/download/jq-{{.LATEST_VERSION}}/jq-linux64"
    cmds:
      - defer: rm -f jq-linux64
      - |
        curl -sLO "{{.DOWNLOAD_URL}}"
        sudo mv jq-linux64 /usr/local/bin/jq
        sudo chown root:root /usr/local/bin/jq
        sudo chmod +x /usr/local/bin/jq
    status:
      - command -v jq
