# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    deps:
      - task: install

  install:
    desc: "Install direnv"
    vars:
      LATEST_VERSION:
        sh: curl -s https://api.github.com/repos/direnv/direnv/releases/latest | jq -r '.tag_name | ltrimstr("v")'
      DOWNLOAD_URL: "https://github.com/direnv/direnv/releases/download/v{{.LATEST_VERSION}}/direnv.linux-amd64"
    run: once
    status:
      - command -v direnv >/dev/null 2>&1
    cmds:
      - curl -sLO "{{.DOWNLOAD_URL}}"
      - chmod +x direnv.linux-amd64
      - sudo mv direnv.linux-amd64 /usr/local/bin/direnv
      - sudo chown root:root /usr/local/bin/direnv
      - sudo chmod 755 /usr/local/bin/direnv
      - |
        if ! grep -q 'eval "$(direnv hook bash)"' "$HOME/.bashrc"; then
          echo 'eval "$(direnv hook bash)"' >> "$HOME/.bashrc"
        fi
      - direnv --version
