# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  install:
    run: once
    status:
      - command -v direnv >/dev/null 2>&1
    cmds:
      - curl -sfL https://direnv.net/install.sh | bash
