name: Test Direnv Installation

on:
  push:
    paths:
      - ".taskfiles/direnv/**"
  pull_request:
    paths:
      - ".taskfiles/direnv/**"
  workflow_dispatch:

jobs:
  test:
    name: Test direnv installation
    runs-on: ubuntu-22.04
    if: github.repository == 'drengskapur/taskfile' && !contains(github.event.act, 'true')
    container:
      image: ubuntu:22.04
      options: --privileged --user root --rm
    env:
      HOME: /root
      PATH: /bin:/usr/bin:/usr/local/bin
    defaults:
      run:
        shell: /bin/sh -e {0}
    steps:
      - uses: actions/checkout@v3

      - name: Install base system utilities
        run: |
          apt-get update
          apt-get install -y bash curl sudo ca-certificates jq

      - name: Cache Task binary
        id: cache-task
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/task
          key: ${{ runner.os }}-task-${{ hashFiles('**/test.yml') }}

      - name: Install Task
        if: steps.cache-task.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          task --version

      - name: Install direnv
        working-directory: .taskfiles/direnv
        run: task install

      - name: Test direnv installation
        run: |
          direnv --version
          # Create a test .envrc file
          echo 'export TEST_VAR="hello"' > .envrc
          direnv allow .
          # Test if direnv loads the environment
          test "$(direnv exec . sh -c 'echo $TEST_VAR')" = "hello"

  test-local:
    name: Test direnv installation (Local)
    runs-on: ubuntu-22.04
    if: contains(github.event.act, 'true')
    container:
      image: ubuntu:22.04
      options: --privileged --user root --rm
    env:
      HOME: /root
      PATH: /bin:/usr/bin:/usr/local/bin
    defaults:
      run:
        shell: /bin/sh -e {0}
    steps:
      - uses: actions/checkout@v3

      - name: Install base system utilities
        run: |
          apt-get update
          apt-get install -y bash curl sudo ca-certificates jq

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          task --version

      - name: Install direnv
        working-directory: .taskfiles/direnv
        run: task install

      - name: Test direnv installation
        run: |
          direnv --version
          # Create a test .envrc file
          echo 'export TEST_VAR="hello"' > .envrc
          direnv allow .
          # Test if direnv loads the environment
          test "$(direnv exec . sh -c 'echo $TEST_VAR')" = "hello"
