# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  HOME:
    sh: echo $HOME
  COMMAND_PREFIX:
    sh: if [ "$(id -u)" != "0" ]; then echo "sudo"; fi

tasks:
  default:
    deps:
      - task: install

  install:
    desc: "Install fnm"
    run: once
    vars:
      INSTALL_DIR: "{{.HOME}}/.fnm"
    status:
      - command -v fnm
    cmds:
      - defer: rm -f install.sh
      # Install dependencies
      - |
        {{.COMMAND_PREFIX}} apt-get update
        {{.COMMAND_PREFIX}} apt-get install -y curl unzip
      # Download and install
      - curl -fsSLo install.sh https://fnm.vercel.app/install
      - bash install.sh --install-dir "{{.INSTALL_DIR}}" --skip-shell
      # Configure shell
      - |
        if ! grep -q 'eval "$(fnm env --use-on-cd)"' "{{.HOME}}/.bashrc"; then
          echo 'export PATH="{{.INSTALL_DIR}}:$PATH"' >> "{{.HOME}}/.bashrc"
          echo 'eval "$(fnm env --use-on-cd)"' >> "{{.HOME}}/.bashrc"
        fi
      # Verify installation
      - source "{{.HOME}}/.bashrc" && fnm --version
