# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    deps: [install]

  install:
    desc: "Install hadolint"
    run: once
    vars:
      COMMAND_PREFIX:
        sh: if [ "$(id -u)" != "0" ]; then echo "sudo"; fi
      LATEST_VERSION:
        sh: curl -s https://api.github.com/repos/hadolint/hadolint/releases/latest | jq -r '.tag_name | ltrimstr("v")'
      DOWNLOAD_URL: "https://github.com/hadolint/hadolint/releases/download/v{{.LATEST_VERSION}}/hadolint-Linux-x86_64"
    status:
      - command -v hadolint
    cmds:
      # Install dependencies
      - |
        {{.COMMAND_PREFIX}} apt-get update
      - |
        {{.COMMAND_PREFIX}} apt-get install -y jq
      # Download and install
      - curl -fsSLo hadolint "{{.DOWNLOAD_URL}}"
      - chmod 755 hadolint
      - |
        {{.COMMAND_PREFIX}} mv hadolint /usr/local/bin/hadolint
      - |
        {{.COMMAND_PREFIX}} chown root:root /usr/local/bin/hadolint
      # Verify installation
      - hadolint --version
