# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

silent: true

tasks:
  clean:
    desc: "Clean up the project"
    cmds:
      - rm -rf debug/

  bun:install:
    desc: "Install Bun."
    run: once
    status:
      - command -v bun >/dev/null 2>&1
    cmds:
      - curl -fsSL https://bun.sh/install | bash

  pip:install:
    desc: "Install pip"
    run: once
    status:
      - python3 -m pip --version >/dev/null 2>&1
    cmds:
      - python3 -m ensurepip

  uv:install:
    desc: "Install uv"
    run: once
    status:
      - python3 -m pip show uv >/dev/null 2>&1
    cmds:
      - python3 -m pip install --user --quiet --no-progress uv

  openssl:rand:base64:
    desc: "Generates a base64 encoded token"
    cmds:
      - openssl rand -base64 {{default "32" .length}} | tr -d '\n'

  hadolint:install:
    desc: "Install hadolint"
    run: once
    status:
      - command -v hadolint >/dev/null 2>&1
    cmds:
      - sudo curl -fsSL https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
      - sudo chown root:root /usr/local/bin/hadolint
      - sudo chmod +x /usr/local/bin/hadolint
      - hadolint --version

  install-jq:
    desc: "Install jq"
    run: once
    vars:
      LATEST_VERSION:
        sh: |
          curl -s https://api.github.com/repos/jqlang/jq/releases/latest | grep '"tag_name":' | sed -E 's/.*"tag_name": "jq-([^"]+)".*/\1/'
      DOWNLOAD_URL: "https://github.com/jqlang/jq/releases/download/jq-{{.LATEST_VERSION}}/jq-linux64"
    cmds:
      - defer: rm -f jq-linux64
      - >-
        curl -sLO "{{.DOWNLOAD_URL}}"
        sudo mv jq-linux64 /usr/local/bin/jq
        sudo chown root:root /usr/local/bin/jq
        sudo chmod +x /usr/local/bin/jq
    status:
      - command -v jq

  install-combine:
    desc: "Install combine"
    run: once
    cmds:
      - >-
        sudo install -m 755 -o root -g root /workspaces/infrastructure/binaries/combine.sh /usr/bin/combine
    status:
      - command -v combine
