# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    deps:
      - task: install

  install:
    desc: "Install commitlint"
    deps:
      - task: _install:node
    vars:
      PACKAGES:
        - "@commitlint/cli@17.8.1"
        - "@commitlint/config-conventional@17.8.1"
    run: once
    status:
      - command -v commitlint >/dev/null 2>&1
    cmds:
      - npm install -g {{.PACKAGES | join " "}}
      - commitlint --version

  _install:node:
    internal: true
    run: once
    status:
      - command -v node >/dev/null 2>&1
    cmds:
      - task: :node:install
