# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Test Commitlint Installation

on:
  push:
    paths:
      - ".taskfiles/commitlint/**"
  pull_request:
    paths:
      - ".taskfiles/commitlint/**"
  workflow_dispatch:

jobs:
  test:
    name: Test Commitlint installation
    runs-on: ubuntu-22.04
    if: ${{ !github.event.act }} # Skip during local testing
    container:
      image: ubuntu:22.04
      options: --privileged --user root
    env:
      HOME: /root
      PATH: /bin:/usr/bin:/usr/local/bin
    defaults:
      run:
        shell: /bin/sh -e {0}
    steps:
      - uses: actions/checkout@v3

      - name: Install base system utilities
        run: |
          apt-get update
          apt-get install -y bash curl sudo

      - name: Install remaining dependencies
        run: |
          apt-get install -y jq unzip

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          task --version

      - name: Install Commitlint
        run: |
          pwd
          ls -la
          task install
          echo "Task exit code: $?"

      - name: Check Commitlint version
        run: |
          which commitlint || true
          commitlint --version

  test-local:
    name: Test Commitlint installation (Local)
    runs-on: ubuntu-22.04
    if: ${{ github.event.act }} # Only run during local testing
    container:
      image: ubuntu:22.04
      options: --privileged --user root
    env:
      HOME: /root
      PATH: /bin:/usr/bin:/usr/local/bin
    defaults:
      run:
        shell: /bin/sh -e {0}
    steps:
      - uses: actions/checkout@v3

      - name: Install base system utilities
        if: ${{ github.event.act }}
        run: |
          apt-get update
          apt-get install -y bash curl sudo

      - name: Install remaining dependencies
        if: ${{ github.event.act }}
        run: |
          apt-get install -y jq unzip

      - name: Install Task
        if: ${{ github.event.act }}
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          task --version

      - name: Install Commitlint
        if: ${{ github.event.act }}
        run: |
          pwd
          ls -la
          echo "Current directory contents:"
          ls -la
          echo "Taskfile contents:"
          cat Taskfile.yml || true
          echo "Running task with verbose output:"
          task --verbose install
          echo "Task exit code: $?"

      - name: Check Commitlint version
        if: ${{ github.event.act }}
        run: |
          which commitlint || true
          commitlint --version
