# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    deps: 
      - task: install

  install:
    desc: "Install Node.js"
    deps: 
      - task: setup-deps
    run: once
    status:
      - command -v node >/dev/null 2>&1
    cmds:
      - task: fnm-install
      - task: fnm-install-node

  setup-deps:
    desc: "Install Ubuntu dependencies"
    internal: true
    run: once
    status:
      - command -v curl unzip >/dev/null 2>&1
    cmds:
      - sudo apt update
      - sudo apt install -y curl unzip

  fnm-install:
    desc: "Install fnm"
    internal: true
    run: once
    status:
      - command -v fnm >/dev/null 2>&1
    cmds:
      - curl -fsSL https://fnm.vercel.app/install | bash
      - echo 'eval "$(fnm env --use-on-cd)"' >> $HOME/.bashrc

  fnm-install-node:
    desc: "Install latest LTS Node.js"
    internal: true
    run: once
    cmds:
      - source $HOME/.bashrc
      - fnm install --lts
      - fnm default lts-latest
      - fnm use lts-latest

  init:
    desc: "Initialize a new Node.js project"
    cmds:
      - npm init -y
