# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    deps:
      - task: install

  install:
    desc: "Install AWS CLI"
    run: once
    vars:
      COMMAND_PREFIX:
        sh: if [ "$(id -u)" != "0" ]; then echo "sudo"; fi
    status:
      - command -v aws
    cmds:
      - defer: rm -rf aws awscliv2.zip
      - |
        {{.COMMAND_PREFIX}} apt-get update
      - |
        {{.COMMAND_PREFIX}} apt-get install -y curl unzip ca-certificates
      - curl -fksSLo awscliv2.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      - unzip -q awscliv2.zip
      - |
        {{.COMMAND_PREFIX}} ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
      - /usr/local/bin/aws --version
