# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    deps: 
      - task: install

  install:
    desc: "Install AWS CLI"
    vars:
      DOWNLOAD_URL: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    run: once
    status:
      - command -v aws >/dev/null 2>&1
    cmds:
      - defer: rm -f awscliv2.zip
      - defer: rm -rf aws
      - curl -sLO "{{.DOWNLOAD_URL}}" -o awscliv2.zip
      - unzip -q awscliv2.zip
      - sudo ./aws/install
      - aws --version
