# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Test AWS CLI Installation

on:
  push:
    paths:
      - ".taskfiles/aws/**"
  pull_request:
    paths:
      - ".taskfiles/aws/**"
  workflow_dispatch:

jobs:
  test:
    name: Test AWS CLI installation
    runs-on: ubuntu-22.04
    if: github.repository == 'drengskapur/taskfile' && !contains(github.event.act, 'true') # Skip during local testing
    container:
      image: ubuntu:22.04
      options: --privileged --user root --rm
    env:
      HOME: /root
      PATH: /bin:/usr/bin:/usr/local/bin
    defaults:
      run:
        shell: /bin/sh -e {0}
    steps:
      - uses: actions/checkout@v3

      - name: Install base system utilities
        run: |
          apt-get update
          apt-get install -y bash curl sudo ca-certificates
          cat /etc/ssl/certs/ca-certificates.crt > /dev/null
          update-ca-certificates

      - name: Install remaining dependencies
        run: |
          apt-get install -y jq unzip

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          task --version

      - name: Install AWS CLI
        run: |
          pwd
          ls -la
          task install
          echo "Task exit code: $?"

      - name: Check AWS CLI version
        run: |
          which aws || true
          aws --version

  test-local:
    name: Test AWS CLI installation (Local)
    runs-on: ubuntu-22.04
    if: contains(github.event.act, 'true') # Only run during local testing
    container:
      image: ubuntu:22.04
      options: --privileged --user root --rm
    env:
      HOME: /root
      PATH: /bin:/usr/bin:/usr/local/bin
    defaults:
      run:
        shell: /bin/sh -e {0}
    steps:
      - uses: actions/checkout@v3

      - name: Install base system utilities
        if: ${{ github.event.act }}
        run: |
          apt-get update
          apt-get install -y bash curl sudo ca-certificates
          cat /etc/ssl/certs/ca-certificates.crt > /dev/null
          update-ca-certificates

      - name: Install remaining dependencies
        if: ${{ github.event.act }}
        run: |
          apt-get install -y jq unzip

      - name: Install Task
        if: ${{ github.event.act }}
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          task --version

      - name: Install AWS CLI
        if: ${{ github.event.act }}
        run: |
          pwd
          ls -la
          echo "Current directory contents:"
          ls -la
          echo "Taskfile contents:"
          cat Taskfile.yml || true
          echo "Running task with verbose output:"
          task --verbose install
          echo "Task exit code: $?"

      - name: Check AWS CLI version
        if: ${{ github.event.act }}
        run: |
          which aws || true
          aws --version
