# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    deps:
      - task: install

  install:
    desc: "Install Go"
    run: once
    vars:
      COMMAND_PREFIX:
        sh: if [ "$(id -u)" != "0" ]; then echo "sudo"; fi
      HOME:
        sh: echo $HOME
      LATEST_VERSION:
        sh: curl -s https://go.dev/dl/?mode=json | jq -r '.[0].version' | sed 's/^go//'
      GOPATH:
        sh: echo $GOPATH || echo $HOME/go
    status:
      - test -x /usr/local/go/bin/go
    cmds:
      # Download and install Go
      - defer: rm -f go.tar.gz
      - curl -fsSLo go.tar.gz "https://go.dev/dl/go{{.LATEST_VERSION}}.linux-amd64.tar.gz"
      - |
        {{.COMMAND_PREFIX}} rm -rf /usr/local/go
      - |
        {{.COMMAND_PREFIX}} tar -C /usr/local -xzf go.tar.gz
      # Create Go workspace
      - mkdir -p {{.GOPATH}}/bin
      - mkdir -p {{.GOPATH}}/src
      - mkdir -p {{.GOPATH}}/pkg
      # Configure environment
      - |
        if ! grep -q "export PATH=\$PATH:/usr/local/go/bin" "$HOME/.profile"; then
          echo 'export PATH=$PATH:/usr/local/go/bin' >> "$HOME/.profile"
        fi
      - |
        if ! grep -q "export GOPATH={{.GOPATH}}" "$HOME/.profile"; then
          echo 'export GOPATH={{.GOPATH}}' >> "$HOME/.profile"
          echo 'export PATH=$PATH:$GOPATH/bin' >> "$HOME/.profile"
        fi
      # Verify installation
      - /usr/local/go/bin/go version
