# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# yaml-language-server: customTags: [!reference]

name: Test Go Installation

on:
  push:
    paths:
      - ".taskfiles/go/**"
  pull_request:
    paths:
      - ".taskfiles/go/**"
  workflow_dispatch:

jobs:
  test:
    name: Test Go installation
    runs-on: ubuntu-22.04
    if: github.repository == 'drengskapur/taskfile' && !contains(github.event.act, 'true') # Skip during local testing
    container:
      image: ubuntu:22.04
      options: --privileged --user root
    env:
      HOME: /root
      GOPATH: /root/go
      PATH: /bin:/usr/bin:/usr/local/bin:/root/.local/go/bin:/root/go/bin
    defaults:
      run:
        shell: /bin/sh -e {0}
    steps:
      - uses: actions/checkout@v3

      - name: Install base system utilities
        run: |
          apt-get update
          apt-get install -y bash curl sudo

      - name: Install remaining dependencies
        run: |
          apt-get install -y jq unzip

      - name: Cache Go installation
        id: cache-go
        uses: actions/cache@v3
        with:
          path: /usr/local/go
          key: ${{ runner.os }}-go-1.24.0

      - name: Cache Task binary
        id: cache-task
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/task
          key: ${{ runner.os }}-task-${{ hashFiles('**/test.yml') }}

      - name: Install Task
        if: steps.cache-task.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          task --version

      - name: Install Go
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: task install

      - name: Check Go version
        run: |
          export PATH="$PATH:/usr/local/go/bin"
          go version

  test-local:
    name: Test Go installation (Local)
    runs-on: ubuntu-22.04
    if: ${{ github.event.act }} # Only run during local testing
    container:
      image: ubuntu:22.04
      options: --privileged --user root
    env:
      HOME: /root
      GOPATH: /root/go
      PATH: /bin:/usr/bin:/usr/local/bin:/root/.local/go/bin:/root/go/bin
    defaults:
      run:
        shell: /bin/sh -e {0}
    steps:
      - uses: actions/checkout@v3

      - name: Install base system utilities
        if: ${{ github.event.act }}
        run: |
          apt-get update
          apt-get install -y bash curl sudo

      - name: Install remaining dependencies
        if: ${{ github.event.act }}
        run: |
          apt-get install -y jq unzip

      - name: Install Task
        if: ${{ github.event.act }}
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          task --version

      - name: Install Go
        if: ${{ github.event.act }}
        run: |
          pwd
          ls -la
          echo "Current directory contents:"
          ls -la
          echo "Taskfile contents:"
          cat Taskfile.yml || true
          echo "Running task with verbose output:"
          task --verbose install
          echo "Task exit code: $?"
          echo "Checking installation:"
          ls -la /usr/local/go || true
          ls -la /usr/local/go/bin || true

      - name: Check Go version
        if: ${{ github.event.act }}
        run: |
          echo "Checking Go installation:"
          ls -la /usr/local/go/bin || true
          /usr/local/go/bin/go version
