name: Taskfile Tests

on:
  workflow_dispatch:
    inputs:
      taskfile:
        description: 'Taskfile to test (leave empty to test all)'
        required: false
        type: string

jobs:
  run-taskfile-tests:
    name: Run Taskfile Tests
    runs-on: ubuntu-latest
    env:
      SHELL: /bin/bash
      USER: runner
      HOME: /home/runner
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        run: |
          curl -sL https://taskfile.dev/install.sh | sh
          sudo mv ./bin/task /usr/local/bin/
          task --version

      - name: Run Tests
        run: |
          if [ -n "${{ inputs.taskfile }}" ]; then
            echo "Testing taskfile: ${{ inputs.taskfile }}"
            task test:${{ inputs.taskfile }}
          else
            echo "Testing all taskfiles"
            task test
          fi
