name: "Install - act"

on:
  push:
    paths:
      - '.taskfiles/act/**'
  pull_request:
    paths:
      - '.taskfiles/act/**'
  workflow_dispatch:

jobs:
  ubuntu-latest:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Configure Git
        run: git config --global --add safe.directory /home/user/taskfile

      - name: Install act
        run: task act:install

      - name: Verify act Installation
        run: task act:verify

  catthehacker:
    name: catthehacker/ubuntu
    runs-on: catthehacker/ubuntu:full
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Configure Git
        run: git config --global --add safe.directory /home/user/taskfile

      - name: Install act
        run: task act:install

      - name: Verify act Installation
        run: task act:verify
