name: Test act Installation

on:
  push:
    paths:
      - '.taskfiles/act/**'
  pull_request:
    paths:
      - '.taskfiles/act/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/drengskapur/taskfile-tester:develop
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: git config --global --add safe.directory /home/user/taskfile

      - name: Install act
        run: task act:install

      - name: Verify act Installation
        run: task act:verify
