name: Test terraform Installation

on:
  push:
    paths:
      - '.taskfiles/terraform/**'
  pull_request:
    paths:
      - '.taskfiles/terraform/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/drengskapur/taskfile-tester:develop
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: git config --global --add safe.directory /home/user/taskfile

      - name: Install terraform
        run: task terraform:install

      - name: Verify terraform Installation
        run: task terraform:verify
