name: Test k3s Installation

on:
  push:
    paths:
      - '.taskfiles/k3s/**'
  pull_request:
    paths:
      - '.taskfiles/k3s/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/drengskapur/taskfile-tester:develop
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: git config --global --add safe.directory /home/user/taskfile

      - name: Install k3s
        run: task k3s:install

      - name: Verify k3s Installation
        run: task k3s:verify
