name: "Install - commitlint"

on:
  push:
    paths:
      - '.taskfiles/commitlint/**'
  pull_request:
    paths:
      - '.taskfiles/commitlint/**'
  workflow_dispatch:

jobs:
  ubuntu-latest:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Configure Git
        run: git config --global --add safe.directory /home/user/taskfile

      - name: Install commitlint
        run: task commitlint:install

      - name: Verify commitlint Installation
        run: task commitlint:verify

  catthehacker:
    name: catthehacker/ubuntu
    runs-on: catthehacker/ubuntu:full
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Configure Git
        run: git config --global --add safe.directory /home/user/taskfile

      - name: Install commitlint
        run: task commitlint:install

      - name: Verify commitlint Installation
        run: task commitlint:verify
