name: "Install - aws"

on:
  push:
    paths:
      - '.taskfiles/aws/**'
  pull_request:
    paths:
      - '.taskfiles/aws/**'
  workflow_dispatch:

jobs:
  ubuntu-latest:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Configure Git
        run: git config --global --add safe.directory /home/user/taskfile

      - name: Install aws
        run: cd .taskfiles/aws && task install

      - name: Verify aws Installation
        run: cd .taskfiles/aws && task verify

  catthehacker:
    name: catthehacker/ubuntu
    runs-on: catthehacker/ubuntu:full
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Configure Git
        run: git config --global --add safe.directory /home/user/taskfile

      - name: Install aws
        run: cd .taskfiles/aws && task install

      - name: Verify aws Installation
        run: cd .taskfiles/aws && task verify
