name: "Install - python3"

on:
  push:
    paths:
      - '.taskfiles/python3/**'
  pull_request:
    paths:
      - '.taskfiles/python3/**'
  workflow_dispatch:

jobs:
  ubuntu-latest:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Configure Git
        run: git config --global --add safe.directory /home/user/taskfile

      - name: Install python3
        run: task python3:install

      - name: Verify python3 Installation
        run: task python3:verify

  catthehacker:
    name: catthehacker/ubuntu
    runs-on: catthehacker/ubuntu:full
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Configure Git
        run: git config --global --add safe.directory /home/user/taskfile

      - name: Install python3
        run: task python3:install

      - name: Verify python3 Installation
        run: task python3:verify
