name: mix

on:
  push:
    paths:
      - '.taskfiles/mix/**'
      - '.github/workflows/mix.yml'
  pull_request:
    paths:
      - '.taskfiles/mix/**'
      - '.github/workflows/mix.yml'
  workflow_dispatch:

jobs:
  test:
    name: Test mix Tasks
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl jq sudo
      - name: Install Task
        run: |
          curl -sL https://taskfile.dev/install.sh | sh
          mv ./bin/task /usr/local/bin/
          task --version
      - name: List tasks
        run: task --dir .taskfiles/mix --list-all
