name: Test node Installation

on:
  push:
    paths:
      - '.taskfiles/node/**'
  pull_request:
    paths:
      - '.taskfiles/node/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/drengskapur/taskfile-tester:develop
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: git config --global --add safe.directory /home/user/taskfile

      - name: Install node
        run: task node:install

      - name: Verify node Installation
        run: task node:verify
