name: Test uv Installation

on:
  push:
    paths:
      - '.taskfiles/uv/**'
  pull_request:
    paths:
      - '.taskfiles/uv/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/drengskapur/taskfile-tester:develop
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: git config --global --add safe.directory /home/user/taskfile

      - name: Install uv
        run: task uv:install

      - name: Verify uv Installation
        run: task uv:verify
